server:
  port: ${PORT:8081}
  servlet:
    context-path: /api
spring:
  application:
    name: smore

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}

  # ?? ?? ???? ?? (??? dev ???? ??)
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: optional:file:.env[.properties]

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: ${OAUTH2_REDIRECT_URI:${baseUrl}/login/oauth2/code/{registrationId}}
            client-name: Google

  data:
    redis:
      host: smore.mooo.com
      port: 6379
      password: Y9v4tRz^jS1wP!kN6x@Lm2QeF8hG%uB
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2
          max-wait: -1ms

    # 캐시 설정
    cache:
      type: redis
      redis:
        time-to-live: 600000  # 기본 TTL 10분
        cache-null-values: false

gms:
  api:
    endpoint: ${GMS_API_ENDPOINT}
    key: ${GMS_API_KEY}

app:
  oauth2:
    frontend:
      success-redirect-url: ${FRONTEND_OAUTH2_SUCCESS_REDIRECT_URL:http://localhost:3000}

jwt:
  access-token-secret: ${ACCESS_TOKEN_SECRET_KEY}
  refresh-token-secret: ${REFRESH_TOKEN_SECRET_KEY}
  access-token-expiration-ms: ${ACCESS_TOKEN_EXP_MS:900000}     # 15분
  refresh-token-expiration-ms: ${REFRESH_TOKEN_EXP_MS:604800000}  # 7일

azure:
  storage:
    account-name: ${AZURE_STORAGE_ACCOUNT_NAME}
    account-key: ${AZURE_STORAGE_ACCOUNT_KEY}
    endpoint: ${AZURE_STORAGE_ENDPOINT}
    container-name: ${AZURE_STORAGE_CONTAINER_NAME}
    sas-token: ${AZURE_STORAGE_SAS_TOKEN}

livekit:
  url: ${LIVEKIT_URL}
  apiKey: ${LIVEKIT_API_KEY}
  apiSecret: ${LIVEKIT_API_SECRET}


logging:
  level:
    io.livekit: DEBUG
    org.oreo.smore: DEBUG
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql.BasicBinder: off

# 성능 측정 설정 (Prometheus + Grafana)
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
      base-path: /actuator
  metrics:
    tags:
      application: ${spring.application.name}
      version: before
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
---

# ??? ??
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://${DEV_DB_HOST}:${DEV_DB_PORT}/${DEV_DB_NAME}?${DEV_DB_PARAMS}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO_SET}
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

---

# ??(Production)? ??
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO_SET}    # ?? ????? validate ?? none ??
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

